- app/controllers/categories_controller.rb
- app/controllers/challenges_controller.rb
- app/models/category.rb
- app/models/challenge.rb
- app/models/challenge_category.rb
- app/models/user.rb
- app/views/categories/index.html.erb
- app/views/challenges/index.html.erb
- config/routes.rb
- db/migrate/20200303171820_create_challenge_categories.rb
- db/migrate/20200303183533_remove_challenge_id_from_categories.rb
- db/schema.rb
- test/models/challenge_category_test.rb
—> added a route to display all the challenges so that if we need all the challenges to be displayed
> Crud actions

- app/controllers/categories_controller.rb
- app/controllers/challenges_controller.rb
- app/views/categories/index.html.erb
- Added a search form in the categories controller index
-  Added an if else logic so that the user can look for the name of a challenge
> search for a challenge

- Gemfile
- Gemfile.lock
- app/models/action.rb
- app/models/action_completion.rb
- app/models/task.rb
- app/models/task_completion.rb
- config/routes.rb
- db/seeds.rb
- drafted the seed
- user info used faker for now (to add associations for users in next iteration)
- updated the model & route to match the name change (task -> action)
> initial seed is drafted

- db/migrate/20200304030106_rename_tasks_to_actions.rb
- db/migrate/20200304031401_add_columns_to_users.rb
- db/migrate/20200304032632_add_difficulty_to_challenges.rb
- db/schema.rb
1. rename tasks (& completion) -> action (& completion) 
2. added column to action: recurring (boolean, default to true)
- this is for **one-timer** actions
3. rename column: emission to impact
4. remove column: user first & last name
5. add column: username & location
6. add column: difficulty: integer (1 is easy, 3 is hard)
updated schema is sent via slack
> schema update

- app/controllers/action_completions_controller.rb
- app/controllers/challenge_subscriptions_controller.rb
- app/controllers/task_completions_controller.rb
- app/controllers/users_controller.rb
- app/models/challenge.rb
- app/views/challenges/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/shared/_menu.html.erb
- config/routes.rb
- db/seeds.rb
Start Now => Create Challenge Subscription
Done (on the action) => Create Action Completion
Also added links to menu
> Challenge sub

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_menu.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/layouts/application.html.erb
- app/views/shared/_menu.html.erb
- app/views/shared/_navbar.html.erb
- Created the menu with links and icons
- Added white and black to config stylesheet
> Created app navigation, with links

- app/controllers/action_completions_controller.rb
- app/controllers/action_settings_controller.rb
- app/controllers/challenge_subscriptions_controller.rb
- app/controllers/pages_controller.rb
- app/models/action.rb
- app/models/action_setting.rb
- app/models/challenge_subscription.rb
- app/models/user.rb
- app/views/pages/dashboard.html.erb
- config/routes.rb
- db/migrate/20200305173602_create_action_settings.rb
- db/migrate/20200305174110_remove_recurring_from_action.rb
- db/schema.rb
- test/controllers/action_settings_controller_test.rb
- test/models/action_setting_test.rb
- added Action Setting
- Action Setting includes Habit (true or false)
- Dashboard View Updated to reflect that
> Action-setting is added. You can change settings for habit

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/users/show.html.erb
Added css colors and started profile design
> Profile header

- app/controllers/action_completions_controller.rb
- app/controllers/action_settings_controller.rb
- app/models/action_setting.rb
- app/views/pages/dashboard.html.erb
- config/routes.rb
- new Post on Action Completion Mass Create
- based on check or not checked on Action Setting for Habits true.
> added habit batch complete

- app/controllers/action_settings_controller.rb
- app/controllers/pages_controller.rb
- app/models/action_setting.rb
- app/views/pages/dashboard.html.erb
- app/views/pages/habit.html.erb
- db/schema.rb
> habit page is in progress

- app/models/action.rb
- db/schema.rb
Pull this and it will let you db:seed after
> association added for action-setting

- app/controllers/action_completions_controller.rb
- checking if the user has existing badges
- modify  some constant names for better understanding
> fixed the problem

- app/controllers/users_controller.rb
- martin found a solution so that the chart works and the tracking works
> fixing the date and the chart

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_menu.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/action_completions_controller.rb
- app/controllers/pages_controller.rb
- app/views/categories/index.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/habit.html.erb
- app/views/shared/_menu.html.erb
- app/views/shared/_navbar.html.erb
navbar for search
Habit page is still at works
> Habit page

- app/assets/stylesheets/components/_profile-badges.scss
- app/assets/stylesheets/pages/_profile.scss
- app/javascript/packs/application.js
- app/views/users/show.html.erb
- Design of the graphs is done
** Need help with adding data to Overall Score
- Co2: current placeholder
> Charts design

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show_challenge.scss
- app/views/challenges/show.html.erb
- style the show page for a challenge 
- now I just need to make it a modal (pop-up)
> structure of the page

- app/views/shared/_menu.html.erb
- Change of icon for the recurring actions
> Recurring actions icon change

- app/assets/stylesheets/components/_card.scss
- app/controllers/action_completions_controller.rb
- app/controllers/action_settings_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/pages/habit.html.erb
- app/views/shared/_menu.html.erb
- icon alignment
- habit front-end framework is there
- added flashes
> Habit secondpush

- app/controllers/challenge_subscriptions_controller.rb
- app/models/challenge_subscription.rb
- app/views/shared/_menu.html.erb
- db/seeds.rb
seed update added user data
navbar icon
> Seed added user records

- app/controllers/buddy_challenges_controller.rb
- app/models/buddy_challenge.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20200309144727_create_buddy_challenges.rb
- db/schema.rb
- test/controllers/buddy_challenges_controller_controller_test.rb
- test/models/buddy_challenge_test.rb
> buddy_challenge model and controller

- app/assets/stylesheets/components/_profile-badges.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/users_controller.rb
- app/javascript/packs/application.js
- app/views/users/show.html.erb
- db/schema.rb
- Changed the place of the charts 
- In the first chart added the month and the day 
- Then I added three span tag weekly / monthly / all time 
--> when you click on each it gets you the data either weekly, monthly or for the hole time you passed on the app 
- In the second chart it's responsive to the exciting data it gives you the impact accordingly to the category 
- Moved the average CO2 at the top to add it into the impact
- Made the badges a little bit bigger so it's relevant
> Profile tracking

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_menu.scss
- app/controllers/action_completions_controller.rb
- app/controllers/action_settings_controller.rb
- app/views/action_completions/mass_create.js.erb
- app/views/action_settings/update_check.js.erb
- app/views/pages/habit.html.erb
- app/views/shared/_menu.html.erb
- config/application.rb
- added AJAX to Habit page.
- Habit Menu is polished.
> Habit menu

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_modal.scss
- app/assets/stylesheets/components/_profile-badges.scss
- app/views/pages/habit.html.erb
- app/views/shared/_challenge_modal.html.erb
- app/views/users/show.html.erb
- Modal css alignment
- Habit css polish
> habit, profile chart modal css polish

- app/views/pages/home.html.erb
> background change

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> homepage update

- app/controllers/action_settings_controller.rb
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
redirect to notification fix (devise feature)
> devise x notification fix

- app/assets/stylesheets/pages/_show_challenge.scss
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/shared/_challenge_modal.html.erb
added user validation - username
Sign up form added username field
Buddy challenge button align
> Post Pitch fix round 2

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
> devise new form

- app/controllers/action_completions_controller.rb
- app/controllers/buddy_challenges_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/javascript/packs/application.js
- app/models/user.rb
- app/views/action_settings/update.js.erb
- app/views/buddy_challenges/index.html.erb
- app/views/shared/_menu.html.erb
- db/seeds.rb
> Little fix

- app/controllers/action_completions_controller.rb
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/action_completion.rb
- db/seeds.rb
- daily impact may have timezone bug, added if statement to guard bug
- seed removed badges.
- badge to be added organically.
> seed and bug fix

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
button is fixed
button removed focus outline
> home btn fixed

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/buddy_challenges/index.html.erb
- app/views/categories/index.html.erb
- app/views/challenges/index.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/habit.html.erb
- app/views/pages/home.html.erb
- app/views/users/show.html.erb
- Key pages are all standardized (not the modals)
- Button home added conditional
> Container standardize

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_menu.scss
- app/assets/stylesheets/components/_modal.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_buddy_challenge.scss
- app/assets/stylesheets/pages/_devise.scss
- app/controllers/buddy_challenges_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/users_controller.rb
- app/views/buddy_challenges/index.html.erb
- app/views/categories/index.html.erb
- app/views/challenges/index.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/habit.html.erb
- app/views/shared/_menu.html.erb
Updated Navbar and Menu
- icon updates
- buddy icon active fix
- integrate it with all pages
- modals are standardized to fit the page
- page scroll fix
> navbar and menu
